package hr.fer.zemris.java.hw05.shell;

/**Class that is used for exceptions generated by errors in {@link ShellEnvironment}
 * @author Fran Kristijan Jelenčić
 *
 */
public class ShellIOException extends RuntimeException {

	/**Constructs a new runtime exception with null as its detail message
	 * 
	 */
	public ShellIOException() {
		super();
	}
	
	/**Constructs a new runtime exception with the specified detail message
	 * @param message
	 */
	ShellIOException(String message){
		super(message);
	}
	
	/**Constructs a new runtime exception with the specified cause
	 * @param cause
	 */
	ShellIOException(Throwable cause){
		super(cause);
	}
}
